const FETCH_PHONES_REQUEST = 'FETCH_PHONES_REQUEST'
const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS'
const FETCH_PHONES_FAILURE = 'FETCH_PHONES_FAILURE'
const PHONE_ADDED_TO_CART = 'PHONE_ADDED_TO_CART'
const PHONE_REMOVED_FROM_CART = 'PHONE_REMOVED_FROM_CART'
const ALL_PHONES_REMOVED_FROM_CART = 'ALL_PHONES_REMOVED_FROM_CART'
export {
    FETCH_PHONES_REQUEST,
    FETCH_PHONES_SUCCESS,
    FETCH_PHONES_FAILURE,
    PHONE_ADDED_TO_CART,
    PHONE_REMOVED_FROM_CART,
    ALL_PHONES_REMOVED_FROM_CART
}