# Generated by Django 3.0.3 on 2020-02-07 14:32

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('gender', models.IntegerField(choices=[(1, 'N/A'), (2, 'Male'), (3, 'Female')], default=1, verbose_name='gender')),
                ('birthYear', models.IntegerField(verbose_name='birthYear')),
                ('eyeColor', models.CharField(max_length=255, verbose_name='eyeColor')),
                ('image', models.ImageField(blank=True, null=True, upload_to=people.models.get_img_path, verbose_name='image')),
            ],
        ),
    ]
