# Generated by Django 3.0.3 on 2020-02-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_remove_people_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'N/A')], default='N', max_length=1),
        ),
    ]
