# Generated by Django 3.0.3 on 2020-02-09 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_people_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='birthYear',
            field=models.CharField(max_length=255, verbose_name='birthYear'),
        ),
    ]
