# Generated by Django 3.0.3 on 2020-02-08 14:49

from django.db import migrations, models
import starships.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Starships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('model', models.CharField(max_length=255, verbose_name='model')),
                ('manufacturer', models.CharField(max_length=255, verbose_name='manufacturer')),
                ('image', models.ImageField(blank=True, null=True, upload_to=starships.models.get_img_path, verbose_name='image')),
            ],
        ),
    ]
